### ISSUE TITLE
conformance: publish image to some hosted public registry

### ISSUE THREAD

**Issue by jdolitsky** [opencontainers/distribution-spec#109]
Based on the call today, I attempted to publish container image to github's package registry (and it worked).

FWIW, all we would need to do is add this to `.github/workflows/conformance-image.yml`:
```
name: conformance-image
on:
  push:
    branches:
      - master
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Publish Image
        uses: matootie/github-docker@v2.2.2
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          context: conformance/
          imageName: distribution-spec-conformance-tests
          imageTag: ${{ github.sha }}
          buildArgs: |
            VERSION=${{ github.sha }}
```

However, after publishing it, it looks like the image require authentication (i.e. is not fully public). Please see this GitHub support topic which has a lot of comments: https://github.community/t5/GitHub-Actions/docker-pull-from-public-GitHub-Package-Registry-fail-with-quot/td-p/32782

So I believe at this point we should proceed with publish to Quay and/or Docker Hub from TravisCI using some organization credentials. cc @vbatts
